#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
fi

SRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TGT=""

install_file() {
  DIR="$( dirname "$1" )"
  mkdir -p "$TGT/$DIR"
  cp "$SRC/$1" "$TGT/$1" && echo "$SRC/$1 => $TGT/$1"
}

install_file "etc/lightdm/lightdm-gtk-greeter.conf"
install_file "usr/share/pixmaps/lightdm/pattern-black.png"
