#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
fi

SRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TGT=""

install_file() {
  DIR="$( dirname "$1" )"
  mkdir -p "$TGT/$DIR"
  cp "$SRC/$1" "$TGT/$1" && echo "$SRC/$1 => $TGT/$1"
}

install_file "etc/X11/xorg.conf.d/00-keyboard.conf"
install_file "etc/X11/xorg.conf.d/50-mouse.conf"
install_file "etc/X11/xorg.conf.d/90-monitor.conf"
