#!/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width   0
bspc config window_gap     30
bspc config top_padding    30
bspc config click_to_focus on

[ -x ~/.screenlayout/default.sh ] && ~/.screenlayout/default.sh
[ -x ~/.fehbg ] && ~/.fehbg
[ -e ~/.config/polybar/config ] && polybar default &
